### ISSUE TITLE
Expanding Questions not obvious

### ISSUE THREAD

**Issue by PJP2810** [omfgtora/Idle-Champions-FAQ#1]
Addition to top text to include a note about clicking questions to expand them.

Also include brief explanation about it being a WIP and if anyone with knowledge is willing/wanting to help to contact me.

**Comment by omfgtora** [comment]
Just let me know what text you'd like added and I will make it happen.

**Comment by omfgtora** [comment]
I made it so that the first question is open by default, which will show the users that there is a hidden section for each question without being navi-like (Hey, listen!) about it.

**Comment by PJP2810** [comment]
Update for heading message:

This is a voluntarily run, Community FAQ that is a work in progress, so if you spot any mistakes,
be them typos or otherwise, or have any questions that you think would be a good addition to this FAQ,
please contact @Archimedes#5179 in the Official Idle Champions Discord Server,
or submit an issue here: https://github.com/omfgtora/Idle-Champions-FAQ/issues
