### ISSUE TITLE
Undefined abbreviations in Q6

### ISSUE THREAD

**Issue by chalemic** [omfgtora/Idle-Champions-FAQ#10]
Question 6 provides guidance on campaign blessing orders and references "T1", "T2", and "T3" blessings without first defining the abbreviation.

Suggestion one: Define the term and place the abbreviation in parentheses at the first occurrence (e.g. "Tier 1 (T1)") 

Suggestion two: Add the abbreviation to the list in question 5, in addition to defining it inside the question.

**Comment by omfgtora** [comment]
Thank you. This is actually a duplicate issue of #8. I will move your suggestions there.
