### ISSUE TITLE
Q6 Elaboration

### ISSUE THREAD

**Issue by PJP2810** [omfgtora/Idle-Champions-FAQ#8]
Forgot to specify T1 Global *Blessing* etc.

Reword parts to make it clear

**Comment by omfgtora** [comment]
> Question 6 provides guidance on campaign blessing orders and references "T1", "T2", and "T3" blessings without first defining the abbreviation.

>Suggestion one: Define the term and place the abbreviation in parentheses at the first occurrence (e.g. "Tier 1 (T1)")

>Suggestion two: Add the abbreviation to the list in question 5, in addition to defining it inside the question.
@chalemic

**Comment by PJP2810** [comment]
Question 6 New answer:

You can play the campaigns in whichever order you like, and do bits of both interchangeably if you want to. However, if you wish to be more optimal with your Campaign order choice, the most valuable reward for progressing within Permanent Campaigns is the ability to purchase Global Blessings. However, in order to both progress to higher Zones (allowing faster Gold, and therefore Favour, earnings), and to unlock the higher Teir Blessings, you much purchase a minimum number of Blessings of the lower Tiers. By default, a Warning is turned on within Idle Champions that will trigger if you attempt to spend more than 20% of your current Favour, which is rarely advisable to ignore.
Due to difference Global Blessings being available for each Permanent Campaign, and set at different Favour Costs, there is a generally agreed upon best order to progress when purchasing these Global Blessings:

Grand Tour of the Sword Coast (Torm) - Tier 1 (T1) Global Blessing - Double Damage
Additionally, buying the 'Divine Blessing' T1 Torm Blessing when the cost of it is <=2% of the favour gained on your run will gain you more than it costs to purchase.

Tomb of Annihilation (Kelemvor) - T2 Global Blessing - Legendary Champions
Similarly to the 'Divine Blessing' T1 Torm Blessing, 'Golden Riches' is worth buying when its cost <=20% of the favour gained on your run, as it will increase your gained Favour by more than it costs to purchase.

Grand Tour of the Sword Coast (Torm) - T2 Global Blessing - Gem Hunter
'Heavy Hitters' is a much better investment than 'Quick Hitters'. The vast majority of Primary DPS Champions have Base Attack cooldowns of more than 4 seconds, therefore 'Heavy Hitters' benefits your important damage dealing Champions the most.

Tomb of Annihilation (Kelemvor) - T2&T3 Global Blessing - Temporary Worship & Golden Luck
'Womanly Wiles' is better than Showmanship if you use a Female as your Primary DPS. Visa-versa, 'Showmanship' if better than Womanly Wiles if you use a Male as your Primary DPS.
